import Head from 'next/head';
import styles from '@/css/Agendamento.module.css';
import forms from '@/css/Forms.module.css';
import { useState } from 'react';
import ConsultaVacina from '@/components/formularios/ConsultaVacina';
import ConsultaTeste from '@/components/formularios/ConsultaTeste';

const Agendamento = () => {
  const [tab, setTab] = useState('vacina');

  return (
    <>
      <Head>
        <title>INVAC DF - Consulta</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <div className="container">
          <h1 className={`main__titulo_secundario ${styles.main__titulo_agenda}`}>Consulte as doses da vacina que você já tomou e o resultado de testes realizados.</h1>
        </div>
      </main>

      <section>
        <div className="container">
          <ul className={styles.tab_menu}>
            <li><button className={`${styles.tab_menu__btn} ${styles.consulta_btn} ${tab == 'vacina' ? styles.ativo : ''}`} onClick={() => setTab('vacina')}>Consultar Vacina</button></li>
            <li><button className={`${styles.tab_menu__btn} ${styles.consulta_btn} ${tab == 'teste' ? styles.ativo : ''}`} onClick={() => setTab('teste')}>Consultar Teste</button></li>
          </ul>

          {
            tab == 'vacina' ? <ConsultaVacina styles={forms}/> : <ConsultaTeste styles={forms}/>
          }
        </div>
      </section>
    </>
  );
};

export default Agendamento;