import Head from 'next/head';
import styles from '@/css/Disponibilidade.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';
import useFetch from '@/public/js/useFetch';
import DisponibilidadeLista from '@/components/Disponibilidade/DisponibilidadeLista';
import Footer from '@/components/Footer';

const Disponibilidade = () => {
  const { query } = useRouter();

  const { data, isPending, error } = useFetch('https://api.npoint.io/602d6184ba6fe5909c09/regioes_administrativas');


  return (
    <>
      <Head>
        <title>INVAC DF - Disponibilidade de Vacinas e Testes</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <div className="container">
          <h1 className='main__titulo'>Confira os lugares com disponibilidade e faça o agendamento.</h1>

          <Link href='/agendamento' className={`btn_principal ${styles.main_btn}`}>Quero agendar</Link>
        </div>
      </main>

      <section>
        <div className="container">
          {error && <div className='container'>{error}</div>}
          {isPending && <div className='container'>Loading...</div>}
          {data && <DisponibilidadeLista data={data} styles={styles} query={query}/>}
  
        </div>
      </section>

      <Footer />
    </>
  );
};

export default Disponibilidade;