import Head from 'next/head';
import styles from '@/css/Faq.module.css';
import Footer from '@/components/Footer';
import FAQs from '@/components/FAQs';
import BannerInformativo from '@/components/BannerInformativo';
import { useEffect } from 'react';

const Faq = () => {

  //gambiarra porque precisava mudar a cor de fundo do header, mas não consigo acessar ele deste arquivo (porque ele tá no componente Layout)
  useEffect(() => {
    document.querySelector('header').classList.add('gradiente_verde');
  }, []);

  return (
    <>
      <Head>
        <title>INVAC DF - Dúvidas Frequentes</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* SEÇÃO INICIAL */}
      <main className={`main ${styles.main}`}>
        <div className="container">
          <div className='main_call'>
            <h1 className='main__titulo_secundario'>Tire suas dúvidas em relação às vacinas e aos testes de Covid-19.</h1>
          </div>
        </div>
      </main>

      <FAQs styles={styles} />

      <BannerInformativo titulo='Mapa de Casos'>
        <li><a href="https://www.saude.df.gov.br/faq-covid-19" target="_blank" rel="noopener noreferrer">Dúvidas frequentes sobre Covid-19 - SES-DF</a></li>
        <li><a href="https://portal.fiocruz.br/coronavirus/perguntas-e-respostas" target="_blank" rel="noopener noreferrer">Perguntas e respostas sobre Covid-19 - Fiocruz</a></li>
      </BannerInformativo>

      <Footer />
    </>
  );
};

export default Faq;