import Head from 'next/head';
import Link from 'next/link';
import styles from '@/css/Index.module.css';
import DisponiveisLista from '@/components/DisponiveisLista';
import { addComma } from '@/public/js/globalFunctions';
import useFetch from '@/public/js/useFetch';
import Footer from '@/components/Footer';
import CasosLista from '@/components/CasosLista';

export default function Home() {
  const { data, isPending, error } = useFetch('https://api.npoint.io/602d6184ba6fe5909c09');

  return (
    <>
      <Head>
        <title>INVAC - DF</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* SEÇÃO INICIAL */}
      <main className='main'>
        <div className="container">
          <h1 className='main__titulo'>Marque suas vacinas e testes de COVID.</h1>

          <Link href='/agendamento' className="btn_principal index_main__btn">Fazer agendamento</Link>
        </div>
      </main>

      {/* DISPONIBILIDADE DE VACINAS E TESTES */}
      {error && <div className='container'>{error}</div>}
      {isPending && <div className='container'>Loading...</div>}
      {data && <DisponiveisLista props={data} styles={styles} />}


      <section className={styles.consulta}>
        <div className="container">
          <h2>Consulte os resultados dos seus testes e a sua carteira de vacinação contra a COVID-19.</h2>
          <Link href='/consulta' className={`btn_principal ${styles.consulta_btn}`}>Consultar!</Link>
        </div>
      </section>

      {/* CASOS DE COVID NO ULTIMO MES */}
      <section className={styles.casos_covid}>
        <div className="container">
          <h2>Veja casos da COVID do último mês na sua região!</h2>

          {data && <CasosLista data={data} styles={styles}/>} 
        </div>
      </section>

      {/* DADOS VACINAIS DF */}
      <section className={styles.dados_vacinais}>
        <div className="container">
          <h2 className={styles.dados_vacinais__h2}>Dados vacinais do Distrito Federal</h2>

          <ul className={styles.dados_lista}>

            <li className={styles.card}>
              <p className={styles.card__p}>Total de Doses Aplicadas</p>
              <span className={styles.card__span}>{data && addComma(data.dados_vacinais_df.total_doses)}</span>
            </li>

            <li className={styles.card}>
              <p className={styles.card__p}>1ª Dose</p>
              <span className={styles.card__span}>{data && addComma(data.dados_vacinais_df.dose_1)}</span>
            </li>

            <li className={styles.card}>
              <p className={styles.card__p}>2ª Dose</p>
              <span className={styles.card__span}>{data && addComma(data.dados_vacinais_df.dose_2)}</span>
            </li>

            <li className={styles.card}>
              <p className={styles.card__p}>3ª Dose</p>
              <span className={styles.card__span}>{data && addComma(data.dados_vacinais_df.reforco_1)}</span>
            </li>
          </ul>

          <Link href='#' className={`btn_principal ${styles.ver_todas_doses}`}>Ver todas as doses aplicadas</Link>
        </div>
      </section>

      <section className={styles.secao_duvidas}>
        <div className="container">
          <h2>Dúvidas sobre a vacina?</h2>
          <p className={styles.secao_duvidas__p}>Separamos todas as frequentes dúvidas  que as pessoas possuem sobre a vacina e respondemos para que você se manter informado!</p>
          <Link href='/faq' className={`btn_principal ${styles.secao_duvidas__btn}`}>Dúvidas frequentes</Link>
        </div>
      </section>

      <Footer />
    </>
  );
}

